name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image of server
        run: docker build -t frontend-website .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build, tag, and push docker image to Docker Hub
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker image tag frontend-website ${{ secrets.DOCKER_USERNAME }}/frontend-website:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME}}/frontend-website:$IMAGE_TAG
          docker image tag frontend-website ${{ secrets.DOCKER_USERNAME }}/frontend-website:latest